version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logistix-pro:latest
    container_name: logistix-pro
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/public/data
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  app-data:
    name: logistix-pro-data

