services:
  app:
    container_name : Logistix_APP
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public/data:/app/public/data
    environment:
      - NODE_ENV=production

